repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        require_serial: true
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        require_serial: true
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        exclude: migrations/
        types: [python]
        require_serial: true
      - id: toml-sort
        name: toml-sort
        entry: poetry run toml-sort --all --in-place
        language: system
        exclude: poetry.lock
        types: [toml]
        require_serial: true
