# Generated by Django 4.1.1 on 2022-09-12 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_k", "0004_remove_notification_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendlist",
            name="friend",
        ),
        migrations.AddField(
            model_name="friendlist",
            name="reader",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="who_met_before",
                to=settings.AUTH_USER_MODEL,
                verbose_name="読んだ人",
            ),
        ),
        migrations.AddField(
            model_name="friendlist",
            name="receiver",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to=settings.AUTH_USER_MODEL,
                verbose_name="読まれた人",
            ),
        ),
    ]
