# Generated by Django 4.1.1 on 2022-09-12 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_k", "0005_remove_friendlist_friend_friendlist_reader_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="post",
            field=models.ForeignKey(
                default=0,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="which_post",
                to="app_k.post",
                verbose_name="ポスト",
            ),
        ),
    ]
