# Generated by Django 4.1.1 on 2022-09-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_k", "0007_alter_notification_post"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customuser",
            table="Users",
        ),
    ]
